[[drone]]
id = 1
connected_node_ids = [11, 3]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [1, 4, 22]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [21, 3]
pdr = 0.0

[[client]]
id = 11
connected_drone_ids = [1]

[[server]]
id = 21
connected_drone_ids = [4]

[[server]]
id = 22
connected_drone_ids = [4]
